apiVersion: v1
kind: Service
metadata:
  labels:
    app: tigergraph
  name: tigergraph
  namespace: default
spec:
  clusterIP: None 
  selector:
    app: tigergraph
  ports:
  - port: 9000
    name: rest
    targetPort: 9000
  - port: 14240
    name: graphstudio
    targetPort: 14240