apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tigergraph
spec:
  volumeClaimTemplates:
    - metadata:
        name: tg-data
        labels:
          app: tigergraph
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "gcp-pd-ssd"
        resources:
          requests:
            storage: 50Gi
